#1
lessons-js/user-management-web pull request #1
Opened 2023-02-02 16:17 UTC by alexvorn

2023-02-02 16:29 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +const fs = require('file-system');
Заменить на импорт

2023-02-02 16:30 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +deleteUser({"id" : 2})
Точно ли нужна эта строка?

2023-02-02 16:31 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +function deleteUser(user) {
Было бы полезно добавить экспорт для функций getUsers, updateUsers, deleteUser и addUser что бы их можно было использовать в других файлах

2023-02-02 16:33 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +        if(e.name === user.name) {
Пользователи с одинаковыми именами допустимы, лучше проверять номер телефона

2023-02-02 16:35 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +    saveFile(users)
Как юзер который вызвал функцию addUser узнает успешно юзер добавлен или нет?

2023-02-02 16:36 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +    saveFile(users)
Как юзер который вызвал функцию deleteUser узнает успешно юзер добавлен или нет?

2023-02-02 16:44 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +            const index = users.indexOf(e, 0);
Второй аргумент в indexOf по умолчанию 0, его можно не передавать. Но в целом в данном случае нет необходимости искать индекс элемента, так как эту информацию можно взять из аргументов метода forEach

2023-02-02 16:47 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +function updateUsers(userId, update) {
Такие же замечания как и в
https://github.com/lessons-js/user-management-web/pull/1/files#r1094793307
https://github.com/lessons-js/user-management-web/pull/1/files#r1094783620

2023-02-02 16:49 UTC, AndrejStarusev commented on server/src/routes/index.ts
> +import '../services/db/db.service';
Данный импорт не нужен, функции из этого файла будут импортиться непосредственно в месте их использования

2023-02-02 16:54 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +function addUser(user) {
Необходимо добавить проверку которая не позволит записать юзера в объекте которого есть поля отличны от тех которые мы ожидаем. Тоже самое при редактировании юзера.

2023-02-02 16:55 UTC, max-baykalov requested changes

2023-02-02 16:55 UTC, max-baykalov commented on server/package.json
> +    "file-system": "^2.2.2",
pls, use the lib insted 
https://www.npmjs.com/package/fs

2023-02-02 16:55 UTC, max-baykalov commented on server/src/services/db/db.service.ts
> +        if(e.name === user.name) {
You have to use Set to create unique colun
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

2023-02-02 16:55 UTC, max-baykalov commented on server/src/routes/index.ts
> +import '../services/db/db.service';
why do you need the import?

2023-02-02 16:55 UTC, max-baykalov commented on server/src/services/db/db.service.ts
> +function addUser(user) {
export?

2023-02-02 16:55 UTC, max-baykalov commented on server/src/services/db/db.service.ts
> +const urlToSave = './src/services/db/users.json';
you can convert the file to class and send config as constructor args

2023-02-02 16:57 UTC, AndrejStarusev commented on server/src/services/db/users.json
> +[
Добавить данный файл в гит игнор что бы он не комитился. В идеале добавить логику, которая при запуске сервера проверяла бы, есть ли такой файл, и если его нет, создавала его.

2023-02-23 13:26 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +        this.dbFolderPass = './db-data/';
Это лучше сделать сразу на строке 7, а эту строку снести, если нет явных причин задавать это значение именно в конструкторе

2023-02-23 13:27 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +    deleteItem(item) {
Функция deleteItem содержит в себе баг - она всегда будет возвращать false

2023-02-23 13:29 UTC, AndrejStarusev commented on server/src/index.ts
> +import './services/db/db.service';
Точно ли нам нужен этот импорт?

2023-02-23 16:36 UTC, alexvorn commented on server/src/index.ts
> +import './services/db/db.service';
да, без него не работает код с файла db.service

2023-02-28 09:57 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
> +    deleteItem(item) {
Предалагю не использовать утверждение "изменение длинны массива" === "юзер удален" в данном случае. Данный код будет работать, но предлагаю сделать через флаг, типа 

`
let isDeleted = false;
forEach(el => {
  if (condition) {
    // delete item
    // isDeleted = true;
  }
})
`

2023-02-28 09:59 UTC, AndrejStarusev commented on server/src/services/db/db.service.ts
>                  const index = this.data.indexOf(e, this.data.indexOf(e));
В чем идея передавать `this.data.indexOf(e)` вторым аргументом?

Предлагаю вообще убрать эту строку и вместо этого взять индекс элемента из функции forEach.

2023-03-01 15:30 UTC, alexvorn commented on server/src/services/db/db.service.ts
>                  const index = this.data.indexOf(e, this.data.indexOf(e));
edit func

2023-03-01 15:30 UTC, alexvorn commented on server/src/services/db/db.service.ts
> +    deleteItem(item) {
edit

2023-03-02 13:22 UTC, max-baykalov approved these changes

2023-03-02 14:28 UTC, AndrejStarusev approved these changes

2023-03-02 14:29 UTC, merged