redirect
lessons-js/user-management-web pull request #4
Opened 2023-02-11 21:10 UTC by MaksimDannik

2023-02-12 12:29 UTC, AndrejStarusev approved these changes

2023-02-12 12:33 UTC, MaksimDannik commented
.

2023-02-13 21:38 UTC, max-baykalov requested changes

2023-02-13 21:38 UTC, max-baykalov commented on client/src/routing/Router.jsx
> +import Users from "../pages/home/Users";
create a new folder for the new page and connect css (e.g. Users.css) file there located in the directory

2023-02-13 21:38 UTC, max-baykalov commented on client/src/routing/Router.jsx
> +    <Route path="/" element={<Navigate replace to="/users" />} />
you could use path="/*" to handle all invalid path

2023-02-13 21:38 UTC, max-baykalov commented on client/src/routing/Router.jsx
> +    <Route path="/users" element={<Users />} />
remove unused Home.jsx file and the folder

2023-02-16 23:11 UTC, max-baykalov approved these changes

2023-02-18 18:59 UTC, merged