added endpoints and validation
lessons-js/user-management-web pull request #6
Opened 2023-02-14 13:41 UTC by RadionVolovoi

2023-02-16 23:19 UTC, max-baykalov requested changes

2023-02-16 23:19 UTC, max-baykalov commented on server/src/routes/UserController.ts
> +  const { id } = req.params;
I would recommend to split each function (midleware) to different files

2023-02-16 23:19 UTC, max-baykalov commented on server/src/routes/UserController.ts
> +import { addUser, getUsers, deleteUser, updateUser } from "#";
What is this dependency? I get the following error in code:

Cannot find module '#' or its corresponding type declarations.ts(2307)

2023-03-03 12:17 UTC, AndrejStarusev approved these changes

2023-03-03 12:18 UTC, AndrejStarusev approved these changes

2023-03-03 12:19 UTC, merged